#!/usr/bin/env sh

echo '🏗️👷 Styling, testing and building your project before committing'


# Check tsconfig standards
npm run check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright.... Code looks good to me... now write git push ... let's see what's wrong with the build. 🤔🤔🤔🤔'

npm run build ||
(
    echo '❌👷🔨❌ Better call Bro... Because your build verification-failed ❌👷🔨❌
            Next build verification-failed: View the errors above to see why.
    '
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'